name: ci

on:
  push:
    branches:
      - kaue

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and test for 'latinoware' context
      - name: Build and test (latinoware context)
        uses: docker/build-push-action@v6
        with:
          target: test
          context: ./latinoware
          dockerfile: ./latinoware/Dockerfile
          load: true

      # Build and push for 'latinoware' context
      - name: Build and push (latinoware context)
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: ./latinoware
          dockerfile: ./latinoware/Dockerfile
          target: final
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lw-teste:latest
